catchafire/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('marketplace.urls', namespace='marketplace')),
    url(r'^.*$', RedirectView.as_view(pattern_name='login', permanent=False)),
]

marketplace/urls.py
from django.urls import path

from . import views


app_name = 'marketplace'

urlpatterns = [
    path('products/', views.list_products, name='products-list'),
    path('products/add/', views.create_product, name='products-add'),
    path('', views.list_offers, name='offers-list'),
    path('offers/add/', views.create_offer, name='offers-add'),
    path('offers/<int:pk>/', views.offer_detail, name='offer-detail'),
    path('demands/', views.list_demand, name='demands-list'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    ONG_MEMBER = 'ong-member'
    DONOR_INSTITUTION = 'donor'

    USER_TYPES = (
        (ONG_MEMBER, ONG_MEMBER),
        (DONOR_INSTITUTION, DONOR_INSTITUTION)
    )

    user_type = models.CharField(
        max_length=16, choices=USER_TYPES, default=DONOR_INSTITUTION
    )
    address = models.TextField()
    image = models.ImageField()

marketplace/models.py
from django.db import models
from django.conf import settings


class Product(models.Model):
    FOOD = 'food'
    CLOTHES = 'clothes'

    CATEGORIES = (
        (FOOD, FOOD),
        (CLOTHES, CLOTHES)
    )
    name = models.CharField(max_length=64)
    category = models.CharField(max_length=32, choices=CATEGORIES, default=FOOD)
    description = models.TextField()
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Offer(models.Model):
    AVAILABLE = 'available'
    UNAVAILABLE = 'unavailable'

    STATUS = (
        (AVAILABLE, AVAILABLE),
        (UNAVAILABLE, UNAVAILABLE)
    )

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    status = models.CharField(max_length=16, choices=STATUS, default=AVAILABLE)
    quantity = models.CharField(max_length=128)
    expiration_date = models.DateTimeField(null=True, blank=True)


class Demand(models.Model):
    REQUESTED = 'requested'
    ACCEPTED = 'accepted'
    DENIED = 'denied'

    STATUS = (
        (REQUESTED, REQUESTED),
        (ACCEPTED, ACCEPTED),
        (DENIED, DENIED)
    )
    petitioner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE)
    status = models.CharField(max_length=16, choices=STATUS, default=REQUESTED)

marketplace/forms.py
from django.forms import ModelForm

from .models import Product, Offer, Demand


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'description', 'name')


class OfferForm(ModelForm):
    class Meta:
        model = Offer
        fields = ('product', 'quantity', 'expiration_date')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['product'].queryset = Product.objects.filter(
                created_by=user
            )


class DemandForm(ModelForm):
    class Meta:
        model = Demand
        fields = ('status', 'offer', 'petitioner')

marketplace/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from accounts.models import User

from .forms import ProductForm, OfferForm, DemandForm
from .models import Product, Offer, Demand


class ListProductsView(ListView):
    model = Product

    def get_queryset(self):
        qs = super(ListProductsView, self).get_queryset()
        return qs.filter(created_by=self.request.user)


list_products = login_required(ListProductsView.as_view())


class CreateProductView(CreateView):
    model = Product
    form_class = ProductForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('marketplace:products-list')


create_product = login_required(CreateProductView.as_view())


class ListOffersView(ListView):
    model = Offer
    template_name = 'offers/list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.user_type == User.DONOR_INSTITUTION:
            queryset = queryset.filter(product__created_by=self.request.user)

        return queryset


list_offers = login_required(ListOffersView.as_view())


class CreateOfferView(CreateView):
    model = Offer
    form_class = OfferForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'user': self.request.user
        })
        return kwargs

    def get_success_url(self):
        return reverse('marketplace:offers-list')


create_offer = login_required(CreateOfferView.as_view())


class OfferDetailView(DetailView):
    model = Offer
    template_name = 'offers/detail.html'

    def post(self, request, *args, **kwargs):
        related_offer = self.get_object()
        Demand.objects.create(
            petitioner=request.user,
            offer=related_offer,
        )
        messages.add_message(
            request,
            messages.INFO,
            'La demanda para este producto fue registrada'
        )
        return redirect(reverse('marketplace:offer-detail', args=(self.kwargs['pk'], )))

    def get_context_data(self, **kw):
        context = super().get_context_data(**kw)
        if self.request.user.user_type == User.ONG_MEMBER:
            context['is_already_demanded'] = Demand.objects.filter(
                petitioner=self.request.user,
                offer=self.object
            ).exists()
        else:
            context["demands"] = Demand.objects.filter(
                offer__product__created_by=self.request.user
            )
        return context


offer_detail = login_required(OfferDetailView.as_view())


class ListDemandView(ListView):
    model = Demand
    form_class = DemandForm

    def get_queryset(self):
        qs = super(ListDemandView, self).get_queryset()
        if self.request.user.user_type == User.DONOR_INSTITUTION:
            qs = qs.filter(offer__product__created_by=self.request.user)

        return qs


list_demand = login_required(ListDemandView.as_view())

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.sketchy.min.css' %}" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">
    {% block body %}{% endblock %}
    {% block footer %}{% endblock %}
</body>
</html>

templates/base_dashboard.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" >
{% endblock %}

{% block title %}Home{% endblock %}

{% block body %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">Los tíos de Vito [{% if user.user_type == 'ong-member' %}ONG{% else %}Proveedor{% endif %}]</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
        {% if user.user_type == 'ong-member' %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'marketplace:offers-list' %}">Ofertas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'marketplace:demands-list' %}">Mis solicitudes</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'marketplace:offers-list' %}">Mis ofertas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'marketplace:products-list' %}">Mis productos</a>
            </li>
        {% endif %}
        </ul>
    </div>
</nav>

{% endblock %}

templates/marketplace/demand_list.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block body_class %}dashboard{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" >
{% endblock %}

{% block title %}Home{% endblock %}

{% block body %}
{{ block.super }}

<div class="container">
    <div class="offers">
        {% for demand in object_list %}
        <div class="row">
            <div class="offer col-md-9">
                <img src="https://i.linio.com/p/62924cd59406cf73df22f5289b619eac-product.jpg" />
                <div class="offer-description">
                    <h3><b>Producto: </b> {{ demand.offer.product.name }}</h3>
                    <div><b>Categoría: </b> {{ demand.offer.product.category }}</div>
                    <div><b>Cantidad ofrecida: </b> {{ demand.offer.quantity }}</div>
                </div>
            </div>
        </div>
        {% empty %}
            <li>No hay demandas registradas.</li>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/marketplace/offer_form.html
{% extends "base_dashboard.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block body %}
{{ block.super }}

<div class="container">
    <h3>Crear oferta</h3>
  <form method="post" class="form">
    {% csrf_token %}
    <div>
      {% bootstrap_field form.product %}
      <a href="{% url 'marketplace:products-add' %}">Agregar producto</a>
    </div>
    <hr />
    <div class="row">
      <div class="col-md-6">{% bootstrap_field form.quantity %}</div>
      <div class="col-md-6">{% bootstrap_field form.expiration_date %}</div>
    </div>

    {% buttons %}
      <button type="submit" class="btn btn-primary">
        Crear oferta
      </button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

templates/marketplace/offer_list.html
<h1>Ofertas</h1>
<ul>
{% for offer in object_list %}
    <li>{{ offer.product.name }}</li>
{% empty %}
    <li>No hay ofertas registrados.</li>
{% endfor %}
</ul>

templates/marketplace/product_form.html
{% extends "base_dashboard.html" %}


{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block body %}
{{ block.super }}
<div class="container">
  <h3>Crear producto</h3>
  <form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_field form.name %}
    {% bootstrap_field form.category %}
    {% bootstrap_field form.description %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        Crear producto
      </button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

templates/marketplace/product_list.html
{% extends "base_dashboard.html" %}

{% block body %}
{{ block.super }}

<div class="container">
    <a href="{% url 'marketplace:products-add' %}" class="btn btn-primary">
        <i class="fas fa-plus"></i> Crear producto
    </a>
    <hr>
    <h1>Productos</h1>
    <ul>
    {% for product in object_list %}
        <li>{{ product.name }}</li>
    {% empty %}
        <li>No hay productos registrados.</li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

templates/offers/detail.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block body_class %}dashboard{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" >
{% endblock %}

{% block title %}Home{% endblock %}

{% block body %}
{{ block.super }}

<div class="container">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}

    <div class="offer-detail row">
        <div class="col-md-9">
            <div class="offer-detail-head">
                <img src="https://i.linio.com/p/62924cd59406cf73df22f5289b619eac-product.jpg" />
                <div class="offer-description">
                    <h3>{{ object.product.name }}</h3>
                    <div>{{ object.product.category }}</div>
                    <div>{{ object.quantity }}</div>
                    <div>{{ object.status }}</div>
                </div>
            </div>
            <p>
                {{ object.product.description }}
            </p>
        </div>
        <div class="col-md-3">
            {% if user.user_type == 'ong-member' and not is_already_demanded %}
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-people-carry"></i> Solicitar producto
                </button>
            </form>
            <hr />
            {% endif %}
            <div class="list-group">
                {% if user.user_type == 'ong-member' and is_already_demanded %}
                <a href="#" class="list-group-item-success list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Solicitud enviada</h5>
                    </div>
                    <small>Hace 15 minutos.</small>
                </a>
                {% endif %}
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Última solicitud</h5>
                    </div>
                    <small>Hace 2 horas.</small>
                </a>
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Número de solicitudes</h5>
                    </div>
                    <small>43</small>
                </a>
            </div>
        </div>
    </div>
    {% if user.user_type == 'donor' %}
    <h3>Lista de solicitantes</h3>
    {% for demand in demands %}
        <div class="demand">
            <div class="list-group">
                <div class="list-group-item">
                    <a class="btn btn-success">Aceptar</a> {{ demand.petitioner }}
                </div>
            </div>
        </div>
    {% empty %}
        <div>Sin solicitantes :'(</div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/offers/list.html
{% extends "base_dashboard.html" %}
{% load static %}

{% block body_class %}dashboard{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" >
{% endblock %}

{% block title %}Home{% endblock %}

{% block body %}
{{ block.super }}

<div class="container">
    <div class="offers">
        {% for offer in object_list %}
        <div class="row">
            <div class="offer col-md-9">
                <img src="https://i.linio.com/p/62924cd59406cf73df22f5289b619eac-product.jpg" />
                <div class="offer-description">
                    <h3><b>Producto: </b> {{ offer.product.name }}</h3>
                    <div><b>Categoría: </b> {{ offer.product.category }}</div>
                    <div><b>Cantidad ofrecida: </b> {{ offer.quantity }}</div>
                </div>
            </div>
            <div class="col-md-3">
                <a class="btn btn-primary" href="{% url 'marketplace:offer-detail' pk=offer.id %}">
                <i class="fas fa-eye"></i> Ver producto</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}